# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.provider "virtualbox"


  config.vm.box = "ubuntu/focal64"
  config.ssh.insert_key = false


  
  config.vm.define "master" do |master|
    master.vm.hostname = "master"
    
    master.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024"]
      vb.customize ["modifyvm", :id, "--cpus", "2"]
    end
    master.vm.synced_folder "workflow/", "/home/vagrant/workflow"
    master.vm.network "private_network", ip: "192.168.50.101", virtualbox__intnet: "tcp_network", nic_type: "virtio"
    master.vm.network "forwarded_port", guest: 4200, host: 4200, host_ip: "127.0.0.1"
    # master.vm.network "public_network", ip: "192.168.0.17"
    master.vm.provision "shell", path: "init_master.sh"
  end

  config.vm.define "worker1" do |worker1|
    worker1.vm.hostname = "worker1"
    
    worker1.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024"]
      vb.customize ["modifyvm", :id, "--cpus", "2"]
    end
    worker1.vm.synced_folder "data/", "/home/vagrant/vagrant_data"
    worker1.vm.network "private_network", ip: "192.168.50.102", virtualbox__intnet: "tcp_network", nic_type: "virtio"
    worker1.vm.provision "shell", path: "init_worker.sh"
  end

  config.vm.define "worker2" do |worker2|
    worker2.vm.hostname = "worker2"
    
    worker2.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024"]
      vb.customize ["modifyvm", :id, "--cpus", "2"]
    end
    worker2.vm.synced_folder "data/", "/home/vagrant/vagrant_data"
    worker2.vm.network "private_network", ip: "192.168.50.103", virtualbox__intnet: "tcp_network", nic_type: "virtio"
    worker2.vm.provision "shell", path: "init_worker.sh"
  end
end

